### ISSUE TITLE
Code review 21-04

### ISSUE THREAD

**Issue by federicaulzurrun** [Cisco-the-wayword/Leaderboard#4]
Hi @Cisco-the-wayword ! First of all congratulation on your project 👍 

![tufoin](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

We suggest you check again these code parts one more time:

@LarryIVC

- Very good work @Cisco-the-wayword but you could consider applying the good practices of HTML by applying semantic elements like the main, header, section, etc.

@federicaulzurrun

- Everything it's great, congratulations on that!
- Following the requirements for this project, try to make the refresh button work, by making it load, when you click on it, the scores that were loaded on the API (previous scores submitted)

**Comment by Cisco-the-wayword** [comment]
Thanks
I've fixed it now
